apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend_web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend_web
  template:
    metadata:
      labels:
        app: frontend_web
    spec:
      containers:
        - name: frontend
          image: likoste1/board-frontend:1.1
          ports:
            - containerPort: 5173
