apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.50.200-192.168.50.250    

# ASUS ip 공유기로 할당받은 ip 주소 확인 필수 - ip addr
# 로컬컴퓨터에 k3s 으로 단일 노드 환경에서 진행을 해서 - istio 와 metalLB 가 결합하지 못함
# istio 를 NodePort 형식으로 진행
